{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "8a5b21fa-cf3f-40e4-ac86-516063989198",
   "metadata": {},
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "\n",
    "Note: Here Exception class refers to the base class for all the exceptions."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3152401b-095b-4eb7-8a8c-f9836b827607",
   "metadata": {},
   "source": [
    "1. Inheriting from the 'Exception' class creates a clear hierarchy of exceptions in the application. This hierarchy helps in organizing and categorizing different types of exceptions based on their functionalities.\n",
    "\n",
    "2. By inheriting from the Exception class, the custom exception classes gain all the properties and behaviors of the base Exception class. This includes the ability to display error messages, traceback information, and other relevant details.\n",
    "\n",
    "3. It allows to handle specific types of errors in a more targeted manner.\n",
    "\n",
    "4. When other developers works with the code, custom exceptions make the code more readable.\n",
    "\n",
    "5. It provides a for adding additional functionality by defining relevant methods."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "68e31d76-986b-4c5d-94d7-dfedfe5dc28f",
   "metadata": {},
   "source": [
    "Q2. Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "9ee0a4a9-c5f9-4d40-af78-0883723f95ef",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'BaseException'>\n",
      "<class 'Exception'>\n",
      "<class 'TypeError'>\n",
      "<class 'decimal.FloatOperation'>\n",
      "<class 'email.errors.MultipartConversionError'>\n",
      "<class 'StopAsyncIteration'>\n",
      "<class 'StopIteration'>\n",
      "<class 'ImportError'>\n",
      "<class 'ModuleNotFoundError'>\n",
      "<class 'zipimport.ZipImportError'>\n",
      "<class 'OSError'>\n",
      "<class 'ConnectionError'>\n",
      "<class 'BrokenPipeError'>\n",
      "<class 'ConnectionAbortedError'>\n",
      "<class 'ConnectionRefusedError'>\n",
      "<class 'ConnectionResetError'>\n",
      "<class 'http.client.RemoteDisconnected'>\n",
      "<class 'BlockingIOError'>\n",
      "<class 'ChildProcessError'>\n",
      "<class 'FileExistsError'>\n",
      "<class 'FileNotFoundError'>\n",
      "<class 'IsADirectoryError'>\n",
      "<class 'NotADirectoryError'>\n",
      "<class 'InterruptedError'>\n",
      "<class 'zmq.error.InterruptedSystemCall'>\n",
      "<class 'PermissionError'>\n",
      "<class 'ProcessLookupError'>\n",
      "<class 'TimeoutError'>\n",
      "<class 'io.UnsupportedOperation'>\n",
      "<class 'signal.itimer_error'>\n",
      "<class 'socket.herror'>\n",
      "<class 'socket.gaierror'>\n",
      "<class 'ssl.SSLError'>\n",
      "<class 'ssl.SSLCertVerificationError'>\n",
      "<class 'ssl.SSLZeroReturnError'>\n",
      "<class 'ssl.SSLWantWriteError'>\n",
      "<class 'ssl.SSLWantReadError'>\n",
      "<class 'ssl.SSLSyscallError'>\n",
      "<class 'ssl.SSLEOFError'>\n",
      "<class 'shutil.Error'>\n",
      "<class 'shutil.SameFileError'>\n",
      "<class 'shutil.SpecialFileError'>\n",
      "<class 'shutil.ExecError'>\n",
      "<class 'shutil.ReadError'>\n",
      "<class 'urllib.error.URLError'>\n",
      "<class 'urllib.error.HTTPError'>\n",
      "<class 'urllib.error.ContentTooShortError'>\n",
      "<class 'gzip.BadGzipFile'>\n",
      "<class 'EOFError'>\n",
      "<class 'asyncio.exceptions.IncompleteReadError'>\n",
      "<class 'RuntimeError'>\n",
      "<class 'RecursionError'>\n",
      "<class 'NotImplementedError'>\n",
      "<class 'zmq.error.ZMQVersionError'>\n",
      "<class 'IPython.core.error.StdinNotImplementedError'>\n",
      "<class '_frozen_importlib._DeadlockError'>\n",
      "<class 'threading.BrokenBarrierError'>\n",
      "<class 'concurrent.futures._base.BrokenExecutor'>\n",
      "<class 'concurrent.futures.thread.BrokenThreadPool'>\n",
      "<class 'asyncio.exceptions.SendfileNotAvailableError'>\n",
      "<class 'pkg_resources.ExtractionError'>\n",
      "<class '_pydevd_bundle.pydevd_vars.VariableError'>\n",
      "<class 'NameError'>\n",
      "<class 'UnboundLocalError'>\n",
      "<class 'AttributeError'>\n",
      "<class 'dataclasses.FrozenInstanceError'>\n",
      "<class 'SyntaxError'>\n",
      "<class 'IndentationError'>\n",
      "<class 'TabError'>\n",
      "<class 'LookupError'>\n",
      "<class 'IndexError'>\n",
      "<class 'KeyError'>\n",
      "<class 'jupyter_client.kernelspec.NoSuchKernel'>\n",
      "<class 'IPython.terminal.pt_inputhooks.UnknownBackend'>\n",
      "<class 'encodings.CodecRegistryError'>\n",
      "<class 'ValueError'>\n",
      "<class 'UnicodeError'>\n",
      "<class 'UnicodeEncodeError'>\n",
      "<class 'UnicodeDecodeError'>\n",
      "<class 'UnicodeTranslateError'>\n",
      "<class 'io.UnsupportedOperation'>\n",
      "<class 'json.decoder.JSONDecodeError'>\n",
      "<class 'ssl.SSLCertVerificationError'>\n",
      "<class 'binascii.Error'>\n",
      "<class '_hashlib.UnsupportedDigestmodError'>\n",
      "<class 'calendar.IllegalMonthError'>\n",
      "<class 'calendar.IllegalWeekdayError'>\n",
      "<class 'dateutil.parser._parser.ParserError'>\n",
      "<class 'pygments.util.ClassNotFound'>\n",
      "<class 'IPython.lib.clipboard.ClipboardEmpty'>\n",
      "<class 'email.errors.MessageDefect'>\n",
      "<class 'email.errors.NoBoundaryInMultipartDefect'>\n",
      "<class 'email.errors.StartBoundaryNotFoundDefect'>\n",
      "<class 'email.errors.CloseBoundaryNotFoundDefect'>\n",
      "<class 'email.errors.FirstHeaderLineIsContinuationDefect'>\n",
      "<class 'email.errors.MisplacedEnvelopeHeaderDefect'>\n",
      "<class 'email.errors.MissingHeaderBodySeparatorDefect'>\n",
      "<class 'email.errors.MultipartInvariantViolationDefect'>\n",
      "<class 'email.errors.InvalidMultipartContentTransferEncodingDefect'>\n",
      "<class 'email.errors.UndecodableBytesDefect'>\n",
      "<class 'email.errors.InvalidBase64PaddingDefect'>\n",
      "<class 'email.errors.InvalidBase64CharactersDefect'>\n",
      "<class 'email.errors.InvalidBase64LengthDefect'>\n",
      "<class 'email.errors.HeaderDefect'>\n",
      "<class 'email.errors.InvalidHeaderDefect'>\n",
      "<class 'email.errors.HeaderMissingRequiredValue'>\n",
      "<class 'email.errors.NonPrintableDefect'>\n",
      "<class 'email.errors.ObsoleteHeaderDefect'>\n",
      "<class 'email.errors.NonASCIILocalPartDefect'>\n",
      "<class 'email.errors.InvalidDateDefect'>\n",
      "<class 'IPython.core.magics.code.MacroToEdit'>\n",
      "<class 'plistlib.InvalidFileException'>\n",
      "<class 'pkg_resources._vendor.more_itertools.more.UnequalIterablesError'>\n",
      "<class 'pkg_resources.extern.packaging.version.InvalidVersion'>\n",
      "<class 'pkg_resources._vendor.packaging._manylinux._ELFFileHeader._InvalidELFFileHeader'>\n",
      "<class 'pkg_resources.extern.packaging.utils.InvalidWheelFilename'>\n",
      "<class 'pkg_resources.extern.packaging.utils.InvalidSdistFilename'>\n",
      "<class 'pkg_resources.extern.packaging.specifiers.InvalidSpecifier'>\n",
      "<class 'pkg_resources.extern.packaging.markers.InvalidMarker'>\n",
      "<class 'pkg_resources.extern.packaging.markers.UndefinedComparison'>\n",
      "<class 'pkg_resources.extern.packaging.markers.UndefinedEnvironmentName'>\n",
      "<class 'pkg_resources.extern.packaging.requirements.InvalidRequirement'>\n",
      "<class 'pkg_resources.RequirementParseError'>\n",
      "<class 'packaging.version.InvalidVersion'>\n",
      "<class 'AssertionError'>\n",
      "<class 'ArithmeticError'>\n",
      "<class 'FloatingPointError'>\n",
      "<class 'OverflowError'>\n",
      "<class 'ZeroDivisionError'>\n",
      "<class 'decimal.DivisionByZero'>\n",
      "<class 'decimal.DivisionUndefined'>\n",
      "<class 'decimal.DecimalException'>\n",
      "<class 'decimal.Clamped'>\n",
      "<class 'decimal.Rounded'>\n",
      "<class 'decimal.Underflow'>\n",
      "<class 'decimal.Overflow'>\n",
      "<class 'decimal.Inexact'>\n",
      "<class 'decimal.Underflow'>\n",
      "<class 'decimal.Overflow'>\n",
      "<class 'decimal.Subnormal'>\n",
      "<class 'decimal.Underflow'>\n",
      "<class 'decimal.DivisionByZero'>\n",
      "<class 'decimal.FloatOperation'>\n",
      "<class 'decimal.InvalidOperation'>\n",
      "<class 'decimal.ConversionSyntax'>\n",
      "<class 'decimal.DivisionImpossible'>\n",
      "<class 'decimal.DivisionUndefined'>\n",
      "<class 'decimal.InvalidContext'>\n",
      "<class 'SystemError'>\n",
      "<class 'encodings.CodecRegistryError'>\n",
      "<class 'ReferenceError'>\n",
      "<class 'MemoryError'>\n",
      "<class 'BufferError'>\n",
      "<class 'Warning'>\n",
      "<class 'UserWarning'>\n",
      "<class 'getpass.GetPassWarning'>\n",
      "<class 'IPython.core.formatters.FormatterWarning'>\n",
      "<class 'EncodingWarning'>\n",
      "<class 'DeprecationWarning'>\n",
      "<class 'IPython.core.interactiveshell.ProvisionalWarning'>\n",
      "<class 'PendingDeprecationWarning'>\n",
      "<class 'SyntaxWarning'>\n",
      "<class 'RuntimeWarning'>\n",
      "<class 'zmq.asyncio.ProactorSelectorThreadWarning'>\n",
      "<class 'dateutil.parser._parser.UnknownTimezoneWarning'>\n",
      "<class 'pkg_resources.PEP440Warning'>\n",
      "<class 'FutureWarning'>\n",
      "<class 'IPython.core.completer.ProvisionalCompleterWarning'>\n",
      "<class 'ImportWarning'>\n",
      "<class 'UnicodeWarning'>\n",
      "<class 'BytesWarning'>\n",
      "<class 'ResourceWarning'>\n",
      "<class 'dateutil.tz.DeprecatedTzFormatWarning'>\n",
      "<class 'pkg_resources.PkgResourcesDeprecationWarning'>\n",
      "<class 'warnings._OptionError'>\n",
      "<class 'runpy._Error'>\n",
      "<class 're.error'>\n",
      "<class 'sre_parse.Verbose'>\n",
      "<class 'locale.Error'>\n",
      "<class 'subprocess.SubprocessError'>\n",
      "<class 'subprocess.CalledProcessError'>\n",
      "<class 'subprocess.TimeoutExpired'>\n",
      "<class 'tokenize.TokenError'>\n",
      "<class 'tokenize.StopTokenizing'>\n",
      "<class 'inspect.ClassFoundException'>\n",
      "<class 'inspect.EndOfBlock'>\n",
      "<class 'traitlets.traitlets.TraitError'>\n",
      "<class 'copy.Error'>\n",
      "<class 'concurrent.futures._base.Error'>\n",
      "<class 'concurrent.futures._base.CancelledError'>\n",
      "<class 'concurrent.futures._base.TimeoutError'>\n",
      "<class 'concurrent.futures._base.InvalidStateError'>\n",
      "<class 'socket._GiveupOnSendfile'>\n",
      "<class 'struct.error'>\n",
      "<class 'binascii.Incomplete'>\n",
      "<class 'asyncio.exceptions.TimeoutError'>\n",
      "<class 'asyncio.exceptions.InvalidStateError'>\n",
      "<class 'asyncio.exceptions.LimitOverrunError'>\n",
      "<class 'asyncio.queues.QueueEmpty'>\n",
      "<class 'asyncio.queues.QueueFull'>\n",
      "<class '_queue.Empty'>\n",
      "<class 'queue.Full'>\n",
      "<class 'ctypes.ArgumentError'>\n",
      "<class 'zmq.error.ZMQBaseError'>\n",
      "<class 'zmq.error.ZMQError'>\n",
      "<class 'zmq.error.ContextTerminated'>\n",
      "<class 'zmq.error.Again'>\n",
      "<class 'zmq.error.InterruptedSystemCall'>\n",
      "<class 'zmq.error.ZMQBindError'>\n",
      "<class 'zmq.error.NotDone'>\n",
      "<class '_pickle.PickleError'>\n",
      "<class '_pickle.PicklingError'>\n",
      "<class '_pickle.UnpicklingError'>\n",
      "<class 'pickle._Stop'>\n",
      "<class 'argparse.ArgumentError'>\n",
      "<class 'argparse.ArgumentTypeError'>\n",
      "<class 'traitlets.config.loader.ConfigError'>\n",
      "<class 'traitlets.config.loader.ConfigLoaderError'>\n",
      "<class 'traitlets.config.loader.ArgumentError'>\n",
      "<class 'traitlets.config.loader.ConfigFileNotFound'>\n",
      "<class 'traitlets.config.configurable.ConfigurableError'>\n",
      "<class 'traitlets.config.configurable.MultipleInstanceError'>\n",
      "<class 'traitlets.config.application.ApplicationError'>\n",
      "<class 'zlib.error'>\n",
      "<class 'tornado.util.TimeoutError'>\n",
      "<class '_curses.error'>\n",
      "<class 'tornado.concurrent.ReturnValueIgnoredError'>\n",
      "<class 'tornado.gen.KeyReuseError'>\n",
      "<class 'tornado.gen.UnknownKeyError'>\n",
      "<class 'tornado.gen.LeakedCallbackError'>\n",
      "<class 'tornado.gen.BadYieldError'>\n",
      "<class 'tornado.gen.ReturnValueIgnoredError'>\n",
      "<class 'tornado.gen.Return'>\n",
      "<class 'jupyter_client.channels.InvalidPortNumber'>\n",
      "<class 'termios.error'>\n",
      "<class '_lzma.LZMAError'>\n",
      "<class 'shutil.RegistryError'>\n",
      "<class 'shutil._GiveupOnFastCopy'>\n",
      "<class 'configparser.Error'>\n",
      "<class 'configparser.NoSectionError'>\n",
      "<class 'configparser.DuplicateSectionError'>\n",
      "<class 'configparser.DuplicateOptionError'>\n",
      "<class 'configparser.NoOptionError'>\n",
      "<class 'configparser.InterpolationError'>\n",
      "<class 'configparser.InterpolationMissingOptionError'>\n",
      "<class 'configparser.InterpolationSyntaxError'>\n",
      "<class 'configparser.InterpolationDepthError'>\n",
      "<class 'configparser.ParsingError'>\n",
      "<class 'configparser.MissingSectionHeaderError'>\n",
      "<class 'jupyter_client.localinterfaces.NoIPAddresses'>\n",
      "<class 'zipfile.BadZipFile'>\n",
      "<class 'zipfile.LargeZipFile'>\n",
      "<class 'entrypoints.BadEntryPoint'>\n",
      "<class 'entrypoints.NoSuchEntryPoint'>\n",
      "<class 'jupyter_client.multikernelmanager.DuplicateKernelError'>\n",
      "<class 'pydoc.ErrorDuringImport'>\n",
      "<class 'executing.executing.NotOneValueFound'>\n",
      "<class 'pure_eval.utils.CannotEval'>\n",
      "<class 'pygments.util.OptionError'>\n",
      "<class 'bdb.BdbQuit'>\n",
      "<class 'pdb.Restart'>\n",
      "<class 'pexpect.exceptions.ExceptionPexpect'>\n",
      "<class 'pexpect.exceptions.EOF'>\n",
      "<class 'pexpect.exceptions.TIMEOUT'>\n",
      "<class 'ptyprocess.util.PtyProcessError'>\n",
      "<class 'IPython.utils.process.FindCmdError'>\n",
      "<class 'IPython.utils.path.HomeDirError'>\n",
      "<class 'IPython.core.profiledir.ProfileDirError'>\n",
      "<class 'IPython.core.error.IPythonCoreError'>\n",
      "<class 'IPython.core.error.TryNext'>\n",
      "<class 'IPython.core.error.UsageError'>\n",
      "<class 'IPython.core.error.StdinNotImplementedError'>\n",
      "<class 'IPython.core.error.InputRejected'>\n",
      "<class 'getopt.GetoptError'>\n",
      "<class 'pygments.filters.ErrorToken'>\n",
      "<class 'IPython.core.prefilter.PrefilterError'>\n",
      "<class 'IPython.core.alias.AliasError'>\n",
      "<class 'IPython.core.alias.InvalidAliasError'>\n",
      "<class 'sqlite3.Error'>\n",
      "<class 'sqlite3.InterfaceError'>\n",
      "<class 'sqlite3.DatabaseError'>\n",
      "<class 'sqlite3.InternalError'>\n",
      "<class 'sqlite3.OperationalError'>\n",
      "<class 'sqlite3.ProgrammingError'>\n",
      "<class 'sqlite3.IntegrityError'>\n",
      "<class 'sqlite3.DataError'>\n",
      "<class 'sqlite3.NotSupportedError'>\n",
      "<class 'sqlite3.Warning'>\n",
      "<class 'IPython.core.interactiveshell.SpaceInInput'>\n",
      "<class 'xml.dom.DOMException'>\n",
      "<class 'xml.dom.IndexSizeErr'>\n",
      "<class 'xml.dom.DomstringSizeErr'>\n",
      "<class 'xml.dom.HierarchyRequestErr'>\n",
      "<class 'xml.dom.WrongDocumentErr'>\n",
      "<class 'xml.dom.InvalidCharacterErr'>\n",
      "<class 'xml.dom.NoDataAllowedErr'>\n",
      "<class 'xml.dom.NoModificationAllowedErr'>\n",
      "<class 'xml.dom.NotFoundErr'>\n",
      "<class 'xml.dom.NotSupportedErr'>\n",
      "<class 'xml.dom.InuseAttributeErr'>\n",
      "<class 'xml.dom.InvalidStateErr'>\n",
      "<class 'xml.dom.SyntaxErr'>\n",
      "<class 'xml.dom.InvalidModificationErr'>\n",
      "<class 'xml.dom.NamespaceErr'>\n",
      "<class 'xml.dom.InvalidAccessErr'>\n",
      "<class 'xml.dom.ValidationErr'>\n",
      "<class 'prompt_toolkit.validation.ValidationError'>\n",
      "<class 'prompt_toolkit.buffer.EditReadOnlyBuffer'>\n",
      "<class 'prompt_toolkit.buffer._Retry'>\n",
      "<class 'prompt_toolkit.layout.layout.InvalidLayoutError'>\n",
      "<class 'prompt_toolkit.renderer.HeightIsUnknownError'>\n",
      "<class 'parso.parser.ParserSyntaxError'>\n",
      "<class 'parso.parser.InternalParseError'>\n",
      "<class 'parso.python.diff._PositionUpdatingFinished'>\n",
      "<class 'jedi.inference.helpers.SimpleGetItemNotFound'>\n",
      "<class 'jedi.inference.utils.UncaughtAttributeError'>\n",
      "<class 'jedi.inference.base_value.HasNoContext'>\n",
      "<class 'jedi.inference.arguments.ParamIssue'>\n",
      "<class 'jedi.api.exceptions._JediError'>\n",
      "<class 'jedi.api.exceptions.InternalError'>\n",
      "<class 'jedi.api.exceptions.WrongVersion'>\n",
      "<class 'jedi.api.exceptions.RefactoringError'>\n",
      "<class 'jedi.api.helpers.OnErrorLeaf'>\n",
      "<class 'jedi.api.environment.InvalidPythonEnvironment'>\n",
      "<class 'email.errors.MessageError'>\n",
      "<class 'email.errors.MessageParseError'>\n",
      "<class 'email.errors.HeaderParseError'>\n",
      "<class 'email.errors.BoundaryError'>\n",
      "<class 'email.errors.MultipartConversionError'>\n",
      "<class 'email.errors.CharsetError'>\n",
      "<class 'uu.Error'>\n",
      "<class 'http.client.HTTPException'>\n",
      "<class 'http.client.NotConnected'>\n",
      "<class 'http.client.InvalidURL'>\n",
      "<class 'http.client.UnknownProtocol'>\n",
      "<class 'http.client.UnknownTransferEncoding'>\n",
      "<class 'http.client.UnimplementedFileMode'>\n",
      "<class 'http.client.IncompleteRead'>\n",
      "<class 'http.client.ImproperConnectionState'>\n",
      "<class 'http.client.CannotSendRequest'>\n",
      "<class 'http.client.CannotSendHeader'>\n",
      "<class 'http.client.ResponseNotReady'>\n",
      "<class 'http.client.BadStatusLine'>\n",
      "<class 'http.client.RemoteDisconnected'>\n",
      "<class 'http.client.LineTooLong'>\n",
      "<class 'IPython.core.magics.code.InteractivelyDefined'>\n",
      "<class 'IPython.terminal.embed.KillEmbedded'>\n",
      "<class 'psutil.Error'>\n",
      "<class 'psutil.NoSuchProcess'>\n",
      "<class 'psutil.ZombieProcess'>\n",
      "<class 'psutil.AccessDenied'>\n",
      "<class 'psutil.TimeoutExpired'>\n",
      "<class 'psutil._pslinux._Ipv6UnsupportedError'>\n",
      "<class 'tornado.queues.QueueEmpty'>\n",
      "<class 'tornado.queues.QueueFull'>\n",
      "<class '_pydev_bundle._pydev_saved_modules.DebuggerInitializationError'>\n",
      "<class 'xml.parsers.expat.ExpatError'>\n",
      "<class 'xmlrpc.client.Error'>\n",
      "<class 'xmlrpc.client.ProtocolError'>\n",
      "<class 'xmlrpc.client.ResponseError'>\n",
      "<class 'xmlrpc.client.Fault'>\n",
      "<class 'pkg_resources._vendor.pyparsing.exceptions.ParseBaseException'>\n",
      "<class 'pkg_resources._vendor.pyparsing.exceptions.ParseException'>\n",
      "<class 'pkg_resources._vendor.pyparsing.exceptions.ParseFatalException'>\n",
      "<class 'pkg_resources._vendor.pyparsing.exceptions.ParseSyntaxException'>\n",
      "<class 'pkg_resources._vendor.pyparsing.exceptions.RecursiveGrammarException'>\n",
      "<class 'pkg_resources.ResolutionError'>\n",
      "<class 'pkg_resources.VersionConflict'>\n",
      "<class 'pkg_resources.ContextualVersionConflict'>\n",
      "<class 'pkg_resources.DistributionNotFound'>\n",
      "<class 'pkg_resources.UnknownExtra'>\n",
      "<class '_pydevd_bundle.pydevd_runpy._Error'>\n",
      "<class '_pydevd_bundle.pydevd_resolver.UnableToResolveVariableException'>\n",
      "<class '_pydev_bundle.pydev_monkey.InvalidTypeInArgsException'>\n",
      "<class 'GeneratorExit'>\n",
      "<class 'SystemExit'>\n",
      "<class 'KeyboardInterrupt'>\n",
      "<class 'asyncio.exceptions.CancelledError'>\n",
      "<class 'pkg_resources._vendor.more_itertools.more.AbortThread'>\n"
     ]
    }
   ],
   "source": [
    "def exception_hierarchy(exception_class):\n",
    "    print(f\"{exception_class}\")\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        exception_hierarchy(subclass)\n",
    "\n",
    "exception_hierarchy(BaseException)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "53fa1e91-571a-4c65-9034-a31fd2dcca73",
   "metadata": {},
   "source": [
    "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e2e516bc-2e21-4c0a-9d36-6ff522d33edc",
   "metadata": {},
   "source": [
    "It is a base class exception that relates with arithmetic operations. It doesn't define any specific error; however, two common exceptions are ArtihmaticError, ZeroDivisionError and OverflowError. The relevant examples are demonstated below-"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "ac005097-be80-4970-aa4d-711582a9d046",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[16], line 10\u001b[0m\n\u001b[1;32m      7\u001b[0m n \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m10\u001b[39m \n\u001b[1;32m      8\u001b[0m d \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m \n\u001b[0;32m---> 10\u001b[0m result \u001b[38;5;241m=\u001b[39m \u001b[43mdivide\u001b[49m\u001b[43m(\u001b[49m\u001b[43mn\u001b[49m\u001b[43m,\u001b[49m\u001b[43md\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     11\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m result\n",
      "Cell \u001b[0;32mIn[16], line 4\u001b[0m, in \u001b[0;36mdivide\u001b[0;34m(x, y)\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mdivide\u001b[39m(x,y):\n\u001b[0;32m----> 4\u001b[0m     result \u001b[38;5;241m=\u001b[39m x\u001b[38;5;241m/\u001b[39my\n\u001b[1;32m      5\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m result\n",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "\"\"\"ZeroDivisionError-This exception is raised when an attempt is made to divide a number \n",
    "by zero\"\"\"\n",
    "\n",
    "def divide(x,y):\n",
    "    result = x/y\n",
    "    return result\n",
    "\n",
    "n = 10 \n",
    "d = 0 \n",
    "\n",
    "result = divide(n,d)\n",
    "return result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "fc5e1b55-a5ef-4057-909c-215b20452e88",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result: 999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999998000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001\n"
     ]
    }
   ],
   "source": [
    "\"\"\"OverflowError- This exception is raised when an arithmetic operation exceeds the limits \n",
    "of the data type.\"\"\"\n",
    "\n",
    "large_number = 999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999\n",
    "\n",
    "try:\n",
    "    result = large_number * large_number\n",
    "except OverflowError as e:\n",
    "    print(\"Error:\", e)\n",
    "else:\n",
    "    print(\"Result:\", result)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "77e76d6a-5fdd-41ad-9126-92d31b415909",
   "metadata": {},
   "source": [
    "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "75fa23e3-e370-49da-b221-f9a437b85f4a",
   "metadata": {},
   "source": [
    "It is a base class for exceptions that occur when a lookup or indexing operation is not successful. The common subclasses of LookupError are KeyError and IndexError."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "588bd42a-7ca5-4086-bdf4-84f0cce7e908",
   "metadata": {},
   "source": [
    "1. KeyError- It is raised when a dictionary is accessed using a key that doesn't exist in the dicitionary.\n",
    "A relevant example is demonstrated below-"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "cd1b7538-6045-4a7d-a6e3-7666ceed9aaf",
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'d'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[2], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m d \u001b[38;5;241m=\u001b[39m {\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124ma\u001b[39m\u001b[38;5;124m\"\u001b[39m:\u001b[38;5;241m1\u001b[39m,\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mb\u001b[39m\u001b[38;5;124m\"\u001b[39m:\u001b[38;5;241m2\u001b[39m,\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mc\u001b[39m\u001b[38;5;124m\"\u001b[39m:\u001b[38;5;241m3\u001b[39m}\n\u001b[0;32m----> 2\u001b[0m \u001b[43md\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43md\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m]\u001b[49m\n",
      "\u001b[0;31mKeyError\u001b[0m: 'd'"
     ]
    }
   ],
   "source": [
    "d = {\"a\":1,\"b\":2,\"c\":3}\n",
    "d[\"d\"]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2319f030-b789-4a0b-b78b-0cd4ff885053",
   "metadata": {},
   "source": [
    "2. IndexError-When an index is called that doesn't exists in any list, tuple etc. IndexError is raised by the program.\n",
    "A relevant example is demonstrated below-"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "7acfdb5d-589b-4769-a4e3-ce79e5101f9c",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[4], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m l \u001b[38;5;241m=\u001b[39m [\u001b[38;5;241m1\u001b[39m,\u001b[38;5;241m2\u001b[39m,\u001b[38;5;241m3\u001b[39m,\u001b[38;5;241m4\u001b[39m,\u001b[38;5;241m5\u001b[39m]\n\u001b[0;32m----> 2\u001b[0m \u001b[43ml\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m]\u001b[49m\n",
      "\u001b[0;31mIndexError\u001b[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "l = [1,2,3,4,5]\n",
    "l[5]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6d2d4167-3a17-4931-a6ff-1b2c53b4cf53",
   "metadata": {},
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bf7c014a-dd81-4a13-bd37-156aacb0035e",
   "metadata": {},
   "source": [
    "1.ImportError- When there is a problem while trying to import a module, ImportError takes place. This can happen for various reasons, such as when the module is not found, there are syntax errors in the module, or there are issues with the module's dependencies. A relevant example is demonstrated below-"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "d4c6fac8-b62d-4ffa-b85a-deab662232a5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ImportError: No module named 'non_existent_module'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ImportError as e:\n",
    "    print(f\"ImportError: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "62cbd077-5a22-4958-96b7-ce936f6b8e1f",
   "metadata": {},
   "source": [
    "2. ModuleNotFoundError- It occurs when python interpreter is unable to locate the module, for which import has been executed. A relevant example is demonstrated below-"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "255596db-9264-415a-bbb4-8057287b1add",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ModuleNotFoundError: No module named 'non_existent_module'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ModuleNotFoundError as e:\n",
    "    print(f\"ModuleNotFoundError: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fd9d8a78-422b-43b5-bf0e-982d2fb0706c",
   "metadata": {},
   "source": [
    "Q6. List down some best practices for exception handling in python. \n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f8a2db13-9fe7-4762-8806-d4fc47c5fd4e",
   "metadata": {},
   "source": [
    "1. Catch specific exception types rather than using a broad except clause. This helps you handle errors more accurately and avoids catching unexpected exceptions.\n",
    "\n",
    "2. If the need arises of handling of different exceptions differently, employing multiple except blocks as a solution proves  to be useful.\n",
    "\n",
    "3. The finally block is used to define code that should be executed regardless of whether an exception was raised or not. It's often used for cleanup tasks like closing files or releasing resources.\n",
    "\n",
    "4. Using the else block with a try statement to specify code that should run only if no exceptions were raised. This is useful for separating the regular code path from the exception handling.\n",
    "\n",
    "5. For more complex applications, defining custom exception classes is one of the effective methods that provide meaningful information about the error with the context.\n",
    "\n",
    "6. Using Python's built-in logging module to log exceptions is a great practice which helps in tracking and diagnosing issues in production environments."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dd6cd1df-647c-4a1a-b381-b3999c857138",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
